version: "3"

services:
  git:
    image: dmccloskey/docker-git
    volumes:
      - //C/Users/domccl/GitHub/docker_git/repositories.csv:/home/user/repositories.csv
    restart: always
    networks:
      - git_network
    
networks:
  git_network:
    ipam:
      config:
        - subnet: 172.23.0.0/16